"""
Check-in services: session creation, response recording, completion.

Key design decisions:
- Follow-ups happen AFTER all widgets are answered (batch, not interstitial)
- Response endpoint is idempotent via get_or_create on CheckinResponse
- Warm contextual greeting generated by LLM, not a static template
"""

import contextlib
import logging

from django.utils import timezone

from apps.checkins.models import CheckinQuestion, CheckinResponse, CheckinSession
from apps.checkins.selection import _derive_phase, _patient_today, evaluate_follow_up_rules, select_daily_questions
from apps.checkins.widgets import build_widget_metadata, update_widget_answered

logger = logging.getLogger(__name__)


class CheckinService:
    """Core service for daily check-in lifecycle."""

    @staticmethod
    def create_daily_session(patient):
        """Create a daily check-in session and emit widget messages.

        Flow:
        1. Select questions via selection engine
        2. Create CheckinSession
        3. Create AgentMessages with widget metadata (inside one agent bubble)
        4. Return the session

        Idempotent: if session already exists for today, returns existing.
        """
        today = _patient_today(patient)

        # Idempotency check
        existing = CheckinSession.objects.filter(patient=patient, date=today).first()
        if existing:
            logger.info("Session already exists for patient %s on %s", patient.id, today)
            return existing

        # Select questions
        selected_codes, rationale = select_daily_questions(patient)
        if not selected_codes:
            logger.info("No questions selected for patient %s on %s", patient.id, today)
            return None

        # Derive context
        pathway_day = patient.days_post_op()
        phase = _derive_phase(patient)

        # Get or create conversation
        from apps.agents.models import AgentConversation

        conversation, _ = AgentConversation.objects.get_or_create(
            patient=patient,
            status="active",
            defaults={"agent_type": "care_coordinator"},
        )

        # Create session
        session = CheckinSession.objects.create(
            patient=patient,
            date=today,
            pathway_day=pathway_day,
            phase=phase,
            questions_selected=selected_codes,
            selection_rationale=rationale,
            status="pending",
            conversation=conversation,
        )

        # Emit widget messages
        _emit_checkin_messages(session, conversation, patient)

        return session

    @staticmethod
    def record_response(session, question_code, value):
        """Record a response to a check-in question.

        Idempotent: if response already exists, returns existing state.
        Auto-completes session when all questions are answered.

        Returns:
            tuple: (CheckinResponse, was_created)
        """
        question = CheckinQuestion.objects.get(code=question_code)

        response, created = CheckinResponse.objects.get_or_create(
            session=session,
            question=question,
            defaults={
                "value": value,
                "raw_text": str(value) if question.response_type == "free_text" else "",
            },
        )

        if not created:
            # Already answered, return existing state
            return response, False

        # Update the widget message metadata to show answered state
        _update_widget_metadata(session, question_code, value)

        # Check if session is now complete
        if session.is_complete:
            CheckinService.complete_session(session)

        return response, True

    @staticmethod
    def complete_session(session):
        """Complete a check-in session.

        Evaluates follow-up rules across ALL responses in batch,
        triggers agent follow-up messages, runs escalation checks.
        """
        if session.status == "completed":
            return

        session.status = "completed"
        session.completed_at = timezone.now()
        session.save(update_fields=["status", "completed_at"])

        # Evaluate follow-up rules in batch
        responses = session.responses.select_related("question").all()
        follow_ups = []

        for resp in responses:
            message = evaluate_follow_up_rules(resp.question, resp.value)
            if message:
                resp.follow_up_triggered = True
                resp.follow_up_response = message
                resp.save(update_fields=["follow_up_triggered", "follow_up_response"])
                follow_ups.append((resp, message))

        # Send follow-up messages and closing
        if session.conversation:
            _send_follow_ups(session, follow_ups)
            _send_closing_message(session, follow_ups)

        # Check for escalation conditions
        _check_escalations(session, responses)

        logger.info(
            "Session %s completed: %d responses, %d follow-ups",
            session.id,
            len(responses),
            len(follow_ups),
        )


def checkin_summary_context(patient):
    """Build context dict for clinician check-in summary and trends partials.

    Returns dict with:
    - recent_sessions: latest 3 CheckinSessions with prefetched responses
    - trend_data: dict of category -> list of {date, value} for numeric responses
    - has_data: bool
    """
    sessions = (
        CheckinSession.objects.filter(patient=patient).order_by("-date")[:3].prefetch_related("responses__question")
    )

    # Build trend data for sparklines (numeric responses only)
    from apps.checkins.models import CheckinResponse

    numeric_types = ["scale_1_5", "scale_1_10"]
    numeric_responses = (
        CheckinResponse.objects.filter(
            session__patient=patient,
            question__response_type__in=numeric_types,
        )
        .select_related("question", "session")
        .order_by("session__date")[:100]
    )

    trend_data = {}
    for resp in numeric_responses:
        cat = resp.question.category
        if cat not in trend_data:
            trend_data[cat] = []
        with contextlib.suppress(TypeError, ValueError):
            trend_data[cat].append(
                {
                    "date": resp.session.date.isoformat(),
                    "value": int(resp.value) if resp.value is not None else None,
                    "question": resp.question.text,
                }
            )

    import json

    return {
        "recent_sessions": sessions,
        "trend_data": trend_data,
        "trend_data_json": json.dumps(trend_data),
        "has_data": sessions.exists(),
    }


# --- Private helpers ---


def _emit_checkin_messages(session, conversation, patient):
    """Create AgentMessages with widget metadata for each selected question.

    Creates one intro message (warm greeting) + one message per widget.
    Widgets render inside the agent bubble in the template.
    """
    from apps.agents.models import AgentMessage

    questions = CheckinQuestion.objects.filter(
        code__in=session.questions_selected,
    ).order_by("priority")

    # Generate warm greeting
    greeting = _generate_greeting(patient, session)

    # Create intro message
    AgentMessage.objects.create(
        conversation=conversation,
        role="assistant",
        content=greeting,
        agent_type="care_coordinator",
        metadata={"type": "checkin_intro", "session_id": str(session.id)},
    )

    # Create widget messages
    for question in questions:
        widget_meta = build_widget_metadata(question, session)
        AgentMessage.objects.create(
            conversation=conversation,
            role="assistant",
            content=question.text,
            agent_type="care_coordinator",
            metadata=widget_meta,
        )

    session.status = "in_progress"
    session.save(update_fields=["status"])


def _generate_greeting(patient, session):
    """Generate a warm, contextual greeting for the check-in.

    Uses LLM with patient preferences and recovery context.
    Falls back to a simple template if LLM fails.
    """
    day = session.pathway_day or "a few"
    name = _get_preferred_name(patient)

    # Try LLM greeting
    try:
        from apps.agents.services import get_llm
        from apps.patients.models import PatientPreferences

        context_parts = [f"Patient name: {name}", f"Day {day} post-op"]

        try:
            prefs = PatientPreferences.objects.get(patient=patient)
            if prefs.recovery_goals:
                context_parts.append(f"Recovery goals: {prefs.recovery_goals}")
        except PatientPreferences.DoesNotExist:
            pass

        prompt = f"""Generate a warm, brief check-in greeting for a cardiac surgery recovery patient.
Context: {", ".join(context_parts)}
Rules:
- Use their name
- Reference their recovery day
- Keep it to 1-2 sentences
- Warm and conversational, like a nurse checking in
- Never say "contact your care team" - you ARE the care team
Example: "Morning Margaret, day 12! Just a few quick questions about how you're doing."
"""
        llm = get_llm()
        response = llm.invoke(prompt)
        content = response.content if hasattr(response, "content") else str(response)
        return content.strip().strip('"')
    except Exception:
        logger.debug("LLM greeting failed, using template fallback")

    # Fallback template
    return f"Hi {name}, day {day} of your recovery! Let me check in with a few quick questions."


def _get_preferred_name(patient):
    """Get the patient's preferred name, with fallback."""
    try:
        from apps.patients.models import PatientPreferences

        prefs = PatientPreferences.objects.get(patient=patient)
        if prefs.preferred_name:
            return prefs.preferred_name
    except PatientPreferences.DoesNotExist:
        pass
    return patient.user.first_name or "there"


def _update_widget_metadata(session, question_code, value):
    """Update the AgentMessage metadata to reflect an answered widget."""
    from apps.agents.models import AgentMessage

    try:
        msg = AgentMessage.objects.filter(
            conversation=session.conversation,
            metadata__question_code=question_code,
            metadata__session_id=str(session.id),
        ).first()

        if msg:
            msg.metadata = update_widget_answered(msg.metadata, value)
            msg.save(update_fields=["metadata"])
    except Exception:
        logger.exception("Failed to update widget metadata for %s", question_code)


def _send_follow_ups(session, follow_ups):
    """Send follow-up messages for adverse answers after session completion."""
    from apps.agents.models import AgentMessage

    if not follow_ups:
        return

    for resp, message in follow_ups:
        AgentMessage.objects.create(
            conversation=session.conversation,
            role="assistant",
            content=message,
            agent_type="care_coordinator",
            metadata={
                "type": "checkin_follow_up",
                "session_id": str(session.id),
                "question_code": resp.question.code,
                "triggered_by_value": resp.value,
            },
        )


def _send_closing_message(session, follow_ups):
    """Send a closing message after all follow-ups."""
    from apps.agents.models import AgentMessage

    if follow_ups:
        content = (
            "Thanks for checking in today. I noticed a few things I'd like to follow up on. "
            "Take your time responding, and I'm here if you need anything."
        )
    else:
        content = "Thanks for checking in! Everything looks good today. I'm here if anything comes up."

    AgentMessage.objects.create(
        conversation=session.conversation,
        role="assistant",
        content=content,
        agent_type="care_coordinator",
        metadata={
            "type": "checkin_closing",
            "session_id": str(session.id),
            "follow_up_count": len(follow_ups),
        },
    )


def _check_escalations(session, responses):
    """Check for escalation conditions across all responses.

    High-priority escalation triggers:
    - Chest pain reported
    - Shortness of breath at rest
    - Wound drainage or opening
    - Pain level >= 8
    """

    escalation_codes = {
        "chest_pain": {"value": "yes", "severity": "high", "reason": "Patient reported chest pain"},
        "shortness_of_breath": {"value": "at_rest", "severity": "high", "reason": "Shortness of breath at rest"},
        "wound_appearance": {
            "value": ["drainage", "opening"],
            "severity": "high",
            "reason": "Wound drainage or separation reported",
        },
        "fever": {"value": "yes", "severity": "medium", "reason": "Patient reported fever/chills"},
    }

    for resp in responses:
        code = resp.question.code

        # Check static escalation rules
        if code in escalation_codes:
            rule = escalation_codes[code]
            expected = rule["value"]
            matches = resp.value == expected if isinstance(expected, str) else resp.value in expected
            if matches:
                resp.escalation_triggered = True
                resp.save(update_fields=["escalation_triggered"])
                _create_alert(session.patient, rule["severity"], rule["reason"], resp)

        # Pain level >= 8 escalation
        if code == "pain_level":
            try:
                if int(resp.value) >= 8:
                    resp.escalation_triggered = True
                    resp.save(update_fields=["escalation_triggered"])
                    _create_alert(
                        session.patient,
                        "medium",
                        f"Patient reported pain level {resp.value}/10",
                        resp,
                    )
            except (TypeError, ValueError):
                pass


def _create_alert(patient, severity, reason, response):
    """Create a clinical alert from a check-in escalation."""
    try:
        from apps.clinical.models import ClinicalAlert

        ClinicalAlert.objects.create(
            patient=patient,
            source="checkin",
            severity=severity,
            title=f"Check-in alert: {reason}",
            details={
                "question_code": response.question.code,
                "question_text": response.question.text,
                "response_value": response.value,
                "session_date": response.session.date.isoformat(),
            },
        )
    except Exception:
        logger.exception("Failed to create clinical alert for patient %s", patient.id)
