# Generated by Django 5.1.15 on 2026-04-03 21:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0007_remove_conversation_escalation_reason'),
        ('pathways', '0003_delete_patientmilestonecheckin'),
        ('patients', '0005_add_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('pain', 'Pain'), ('sleep', 'Sleep'), ('bowel', 'Bowel Function'), ('energy', 'Energy'), ('medication', 'Medication'), ('mood', 'Mood'), ('mobility', 'Mobility'), ('wound', 'Wound Care')], max_length=20)),
                ('text', models.TextField(help_text='Question text shown to the patient')),
                ('response_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('scale_1_5', 'Scale 1-5'), ('scale_1_10', 'Scale 1-10'), ('multiple_choice', 'Multiple Choice'), ('free_text', 'Free Text')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='For multiple_choice: list of {value, label} dicts')),
                ('follow_up_rules', models.JSONField(blank=True, default=list, help_text='Rules that trigger follow-up. Each: {operator, value, message}')),
                ('priority', models.IntegerField(default=5, help_text='1=highest priority for selection (asked first when tied)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checkins_question',
                'ordering': ['category', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='CheckinSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The calendar date this check-in covers')),
                ('pathway_day', models.IntegerField(blank=True, help_text='Days post-op when this session was created', null=True)),
                ('phase', models.CharField(blank=True, default='', max_length=10)),
                ('questions_selected', models.JSONField(blank=True, default=list, help_text='List of question codes selected for this session')),
                ('selection_rationale', models.TextField(blank=True, default='', help_text='LLM reasoning for question selection')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_sessions', to='agents.agentconversation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_sessions', to='patients.patient')),
            ],
            options={
                'db_table': 'checkins_session',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CheckinResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(help_text='The response value (string, int, or structured data)')),
                ('raw_text', models.TextField(blank=True, default='', help_text='Raw text input for free_text responses')),
                ('follow_up_triggered', models.BooleanField(default=False)),
                ('follow_up_response', models.TextField(blank=True, default='', help_text='Agent follow-up message content, if triggered')),
                ('escalation_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_message', models.ForeignKey(blank=True, help_text='The widget message this response was submitted through', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_responses', to='agents.agentmessage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checkins.checkinquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checkins.checkinsession')),
            ],
            options={
                'db_table': 'checkins_response',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PathwayCheckinConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('pain', 'Pain'), ('sleep', 'Sleep'), ('bowel', 'Bowel Function'), ('energy', 'Energy'), ('medication', 'Medication'), ('mood', 'Mood'), ('mobility', 'Mobility'), ('wound', 'Wound Care')], max_length=20)),
                ('min_frequency', models.JSONField(blank=True, default=list, help_text='Frequency floors by phase. E.g. [{"phase":"early","every_n_days":1}]')),
                ('relevance_phase', models.CharField(choices=[('early', 'Early (days 1-7)'), ('middle', 'Middle (days 8-30)'), ('late', 'Late (days 31+)'), ('all', 'All phases')], default='all', max_length=10)),
                ('max_gap_days', models.IntegerField(default=7, help_text='Max days between asks for this category before floor forces it')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_configs', to='pathways.clinicalpathway')),
            ],
            options={
                'db_table': 'checkins_pathway_config',
            },
        ),
        migrations.AddIndex(
            model_name='checkinsession',
            index=models.Index(fields=['patient', '-date'], name='idx_checkin_sess_pt_date'),
        ),
        migrations.AlterUniqueTogether(
            name='checkinsession',
            unique_together={('patient', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='checkinresponse',
            unique_together={('session', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='pathwaycheckinconfig',
            unique_together={('pathway', 'category')},
        ),
    ]
