# Generated by Django 5.1.15 on 2026-03-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('success', models.BooleanField()),
                ('method', models.CharField(choices=[('sms_link', 'SMS Link'), ('manual', 'Manual Entry'), ('magic_link', 'Magic Link')], max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_attempts', to='patients.patient')),
            ],
            options={
                'db_table': 'accounts_auth_attempt',
                'ordering': ['-timestamp'],
            },
        ),
    ]
