# Generated by Django 5.1.15 on 2026-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_phone_number_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Updated by WS consumer heartbeat (30s interval). Used for push routing.', null=True),
        ),
    ]
