#!/usr/bin/env bash
# =============================================================================
# Clintela VM: Passwordless sudo for dev commands
#
# One-time setup. Creates a sudoers drop-in that allows the current user
# to run Docker, apt-get, and systemctl without a password prompt.
#
# Usage:
#   sudo ./setup-sudoers.sh
# =============================================================================
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run with sudo:"
  echo "  sudo ./setup-sudoers.sh"
  exit 1
fi

TARGET_USER="${SUDO_USER:-$(logname)}"
SUDOERS_FILE="/etc/sudoers.d/clintela-dev"

if [ -f "$SUDOERS_FILE" ]; then
  echo "Sudoers file already exists: $SUDOERS_FILE"
  echo "Remove it first if you want to regenerate:"
  echo "  sudo rm $SUDOERS_FILE"
  exit 0
fi

cat > "$SUDOERS_FILE" <<EOF
# Clintela dev environment — passwordless sudo for dev commands
# Generated by setup-sudoers.sh

$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/docker
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/docker-compose
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl start docker
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop docker
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart docker
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl enable docker
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/apt-get
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/sbin/lvextend
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/sbin/resize2fs
EOF

chmod 0440 "$SUDOERS_FILE"

# Validate syntax — if this fails, remove the file to avoid locking out sudo
if ! visudo -cf "$SUDOERS_FILE"; then
  rm -f "$SUDOERS_FILE"
  echo "ERROR: sudoers syntax check failed. File removed."
  exit 1
fi

echo "Sudoers configured for $TARGET_USER:"
echo "  - docker, docker-compose (no password)"
echo "  - systemctl start/stop/restart/enable docker (no password)"
echo "  - apt-get (no password)"
echo "  - lvextend, resize2fs (no password)"
echo ""
echo "All other sudo commands still require a password."
