# Generated by Django 5.1.15 on 2026-03-20 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0001_initial'),
        ('patients', '0003_phase4_caregiver_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(choices=[('follow_up', 'Follow Up'), ('virtual_visit', 'Virtual Visit'), ('check_in', 'Check In'), ('consultation', 'Consultation')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('virtual_visit_url', models.CharField(blank=True, max_length=500)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinicians.clinician')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'db_table': 'clinicians_appointment',
                'ordering': ['scheduled_start'],
                'indexes': [models.Index(fields=['clinician', 'scheduled_start'], name='idx_appt_clinician_start'), models.Index(fields=['patient', 'scheduled_start'], name='idx_appt_patient_start')],
            },
        ),
        migrations.CreateModel(
            name='ClinicianAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_recurring', models.BooleanField(default=True)),
                ('effective_date', models.DateField(blank=True, help_text='For one-off availability overrides', null=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='clinicians.clinician')),
            ],
            options={
                'db_table': 'clinicians_availability',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_recurring', True)), fields=('clinician', 'day_of_week', 'start_time'), name='uq_clinician_recurring_avail')],
            },
        ),
        migrations.CreateModel(
            name='ClinicianNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('quick_note', 'Quick Note'), ('clinical_observation', 'Clinical Observation'), ('follow_up', 'Follow Up'), ('care_plan_note', 'Care Plan Note')], default='quick_note', max_length=25)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clinicians.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_notes', to='patients.patient')),
            ],
            options={
                'db_table': 'clinicians_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='idx_clin_note_patient_created')],
            },
        ),
    ]
