# Generated by Django 5.1.15 on 2026-03-23 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agentmessage_role'),
        ('clinicians', '0002_appointment_clinicianavailability_cliniciannote'),
        ('pathways', '0002_pathwaymilestone_patientmilestonecheckin'),
        ('patients', '0004_add_patient_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ical_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinician',
            name='zoom_link',
            field=models.URLField(blank=True, help_text='Personal Zoom meeting room URL'),
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('milestone', 'Pathway Milestone'), ('escalation', 'System Escalation'), ('clinician', 'Clinician Requested')], max_length=20)),
                ('reason', models.TextField()),
                ('appointment_type', models.CharField(choices=[('follow_up', 'Follow Up'), ('virtual_visit', 'Virtual Visit'), ('check_in', 'Check In'), ('consultation', 'Consultation')], default='follow_up', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('earliest_notify_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='clinicians.appointment')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='clinicians.clinician')),
                ('escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.escalation')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pathways.pathwaymilestone')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinicians_appointment_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_appt_req_patient_status'), models.Index(fields=['earliest_notify_at', 'status'], name='idx_appt_req_notify')],
            },
        ),
    ]
