# Generated by Django 5.1.15 on 2026-03-20 12:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('acc_guideline', 'ACC Guideline'), ('clinical_research', 'Clinical Research'), ('hospital_protocol', 'Hospital Protocol')], max_length=30)),
                ('url', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_sources', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, help_text='NULL = global (e.g. ACC guidelines), non-null = tenant-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='patients.hospital')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_knowledge_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_source',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('chunk_metadata', models.JSONField(blank=True, default=dict, help_text='Section path, page numbers, recommendation class/level')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('token_count', models.IntegerField(default=0)),
                ('content_hash', models.CharField(help_text='SHA-256 hash of content for deduplication', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgesource')),
            ],
            options={
                'db_table': 'knowledge_document',
                'ordering': ['source', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(help_text="The patient's question that had no good match")),
                ('max_similarity', models.FloatField(default=0.0, help_text='Best similarity score from retrieval (0 if no results)')),
                ('agent_type', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gaps', to='patients.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gaps', to='patients.patient')),
            ],
            options={
                'db_table': 'knowledge_gap',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'created_at'], name='idx_kg_hospital_created')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['hospital', 'is_active'], name='idx_ks_hospital_active'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['source_type'], name='idx_ks_source_type'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_kd_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_kd_search_vector'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['source', 'is_active'], name='idx_kd_source_active'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='uq_kd_source_content_hash'),
        ),
    ]
