# Generated by Django 5.1.15 on 2026-03-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDashboardProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Knowledge Dashboard',
                'verbose_name_plural': 'Knowledge Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge.knowledgesource',),
        ),
    ]
