# Generated by Django 5.1.15 on 2026-03-23 01:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0005_alter_agentmessage_role'),
        ('patients', '0004_add_patient_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientClinicalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('vital_signs', models.JSONField(blank=True, default=dict, help_text='Latest values: {"hr": {"value": 72, "at": "...", "trend": "stable"}, ...}')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, help_text='Composite 0-100 risk score', max_digits=5)),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='Contributing factors with weights')),
                ('trajectory', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('concerning', 'Concerning'), ('deteriorating', 'Deteriorating')], default='stable', max_length=20)),
                ('active_alerts_count', models.IntegerField(default=0, help_text='Denormalized count of unresolved alerts')),
                ('last_ehr_sync', models.DateTimeField(blank=True, help_text='When EHR data was last pulled (future)', null=True)),
                ('data_completeness', models.DecimalField(decimal_places=2, default=0, help_text='0.0-1.0, how much data we have vs. expected', max_digits=3)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_snapshot', to='patients.patient')),
            ],
            options={
                'db_table': 'clinical_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ClinicalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold'), ('trend', 'Trend'), ('missing_data', 'Missing Data'), ('combination', 'Combination')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('yellow', 'Yellow - Needs Attention'), ('orange', 'Orange - Escalated'), ('red', 'Red - Critical')], max_length=10)),
                ('rule_name', models.CharField(help_text='Identifier of the rule that fired (e.g., weight_gain_3day)', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rule_rationale', models.TextField(blank=True, help_text='FDA-aligned plain-language explanation of why this alert fired')),
                ('trigger_data', models.JSONField(blank=True, default=dict, help_text='The observations that triggered this alert')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_action_taken', models.CharField(blank=True, help_text='e.g., messaged_patient, notified_clinician', max_length=50)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_clinical_alerts', to=settings.AUTH_USER_MODEL)),
                ('escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_alerts', to='agents.escalation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_alerts', to='patients.patient')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_clinical_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_alert_patient_status'), models.Index(fields=['patient', 'rule_name', 'status'], name='idx_alert_patient_rule_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('patient', 'rule_name'), name='unique_active_alert_per_rule')],
            },
        ),
        migrations.CreateModel(
            name='ClinicalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept_id', models.IntegerField(db_index=True, help_text='OMOP concept ID (e.g., 3027018 = Heart Rate)')),
                ('concept_name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value_text', models.CharField(blank=True, help_text='For non-numeric observations', max_length=500)),
                ('unit', models.CharField(max_length=20)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('wearable', 'Wearable Device'), ('manual', 'Manual Entry'), ('ehr', 'EHR/OMOP'), ('patient_reported', 'Patient Reported'), ('calculated', 'Calculated')], max_length=20)),
                ('source_device', models.CharField(blank=True, help_text='e.g., Apple Watch, Withings Scale', max_length=100)),
                ('quality', models.CharField(choices=[('verified', 'Verified'), ('estimated', 'Estimated'), ('self_reported', 'Self-Reported')], default='verified', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_anomalous', models.BooleanField(default=False, help_text='Flagged by rules engine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_observations', to='patients.patient')),
            ],
            options={
                'db_table': 'clinical_observation',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['patient', 'concept_id', 'observed_at'], name='idx_obs_patient_concept_time'), models.Index(fields=['patient', 'observed_at'], name='idx_obs_patient_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('value_numeric__isnull', True), ('value_text', ''), _negated=True), name='obs_value_not_empty')],
            },
        ),
    ]
