# Generated by Django 5.1.15 on 2026-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0005_add_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalobservation',
            name='source',
            field=models.CharField(choices=[('wearable', 'Wearable Device'), ('manual', 'Manual Entry'), ('ehr', 'EHR/OMOP'), ('patient_reported', 'Patient Reported'), ('calculated', 'Calculated'), ('healthkit', 'Apple HealthKit'), ('health_connect', 'Android Health Connect')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='clinicalobservation',
            constraint=models.UniqueConstraint(fields=('patient', 'concept_id', 'observed_at', 'source'), name='uniq_obs_patient_concept_time_source'),
        ),
    ]
