# Generated by Django 5.1.15 on 2026-03-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('supervisor', 'Supervisor'), ('care_coordinator', 'Care Coordinator'), ('nurse_triage', 'Nurse Triage'), ('documentation', 'Documentation'), ('specialist', 'Specialist')], max_length=20)),
                ('message_text', models.TextField()),
                ('agent_response', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('escalation_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to='patients.patient')),
            ],
            options={
                'db_table': 'agents_conversation',
                'ordering': ['-created_at'],
            },
        ),
    ]
