# Generated by Django 5.1.15 on 2026-03-18 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('supervisor', 'Supervisor'), ('care_coordinator', 'Care Coordinator'), ('nurse_triage', 'Nurse Triage'), ('documentation', 'Documentation'), ('specialist_cardiology', 'Cardiology Specialist'), ('specialist_social_work', 'Social Work Specialist'), ('specialist_nutrition', 'Nutrition Specialist'), ('specialist_pt_rehab', 'PT/Rehab Specialist'), ('specialist_palliative', 'Palliative Care Specialist'), ('specialist_pharmacy', 'Pharmacy Specialist')], default='supervisor', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('escalated', 'Escalated')], default='active', max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('tool_invocations', models.JSONField(blank=True, default=list)),
                ('escalation_reason', models.TextField(blank=True)),
                ('llm_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to='patients.patient')),
            ],
            options={
                'db_table': 'agents_conversation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('agent_type', models.CharField(blank=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_audit_logs', to='patients.patient')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='agents.agentconversation')),
            ],
            options={
                'db_table': 'agents_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('agent_type', models.CharField(blank=True, choices=[('supervisor', 'Supervisor'), ('care_coordinator', 'Care Coordinator'), ('nurse_triage', 'Nurse Triage'), ('documentation', 'Documentation'), ('specialist_cardiology', 'Cardiology Specialist'), ('specialist_social_work', 'Social Work Specialist'), ('specialist_nutrition', 'Nutrition Specialist'), ('specialist_pt_rehab', 'PT/Rehab Specialist'), ('specialist_palliative', 'Palliative Care Specialist'), ('specialist_pharmacy', 'Pharmacy Specialist')], max_length=30)),
                ('routing_decision', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('escalation_triggered', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agentconversation')),
            ],
            options={
                'db_table': 'agents_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_summary', models.TextField(blank=True)),
                ('recent_symptoms', models.JSONField(blank=True, default=list)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('recovery_phase', models.CharField(blank=True, max_length=20)),
                ('tools_invoked', models.JSONField(blank=True, default=list)),
                ('escalation_history', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='agents.agentconversation')),
            ],
            options={
                'db_table': 'agents_conversation_state',
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('routine', 'Routine')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('conversation_summary', models.TextField(blank=True)),
                ('patient_context', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escalations', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='agents.agentconversation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='patients.patient')),
            ],
            options={
                'db_table': 'agents_escalation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['patient', 'status'], name='idx_agent_conv_patient_status'),
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['created_at'], name='idx_agent_conv_created'),
        ),
        migrations.AddIndex(
            model_name='agentauditlog',
            index=models.Index(fields=['patient', 'created_at'], name='idx_audit_patient_created'),
        ),
        migrations.AddIndex(
            model_name='agentauditlog',
            index=models.Index(fields=['created_at'], name='idx_audit_created'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_agent_msg_conv_created'),
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['status', 'severity'], name='idx_escalation_status_severity'),
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['patient', 'created_at'], name='idx_escalation_patient_created'),
        ),
    ]
