# Generated by Django 5.1.15 on 2026-03-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Combined similarity score from hybrid search')),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('agent_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='agents.agentmessage')),
                ('knowledge_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='knowledge.knowledgedocument')),
            ],
            options={
                'db_table': 'agents_message_citation',
            },
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='cited_documents',
            field=models.ManyToManyField(blank=True, through='agents.MessageCitation', to='knowledge.knowledgedocument'),
        ),
        migrations.AddIndex(
            model_name='messagecitation',
            index=models.Index(fields=['knowledge_doc'], name='idx_citation_knowledge_doc'),
        ),
        migrations.AddConstraint(
            model_name='messagecitation',
            constraint=models.UniqueConstraint(fields=('agent_message', 'knowledge_doc'), name='uq_citation_message_doc'),
        ),
    ]
