# Generated by Django 5.1.15 on 2026-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_messagecitation_agentmessage_cited_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='escalation_type',
            field=models.CharField(choices=[('clinical', 'Clinical'), ('specialist_referral', 'Specialist Referral'), ('social_work', 'Social Work'), ('pharmacy_consult', 'Pharmacy Consult')], default='clinical', max_length=30),
        ),
        migrations.AddField(
            model_name='escalation',
            name='priority_score',
            field=models.FloatField(default=0.0, help_text='Computed from severity + wait time + patient status'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='SLA tracking: when this escalation must be addressed', null=True),
        ),
    ]
