# Generated by Django 5.1.15 on 2026-03-20 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_phase4_lifecycle_escalation'),
        ('clinicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='clinician',
            field=models.ForeignKey(blank=True, help_text='Set for clinician research conversations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_conversations', to='clinicians.clinician'),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='paused_by',
            field=models.ForeignKey(blank=True, help_text='Clinician who has taken control of this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentconversation',
            name='agent_type',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('care_coordinator', 'Care Coordinator'), ('nurse_triage', 'Nurse Triage'), ('documentation', 'Documentation'), ('specialist_cardiology', 'Cardiology Specialist'), ('specialist_social_work', 'Social Work Specialist'), ('specialist_nutrition', 'Nutrition Specialist'), ('specialist_pt_rehab', 'PT/Rehab Specialist'), ('specialist_palliative', 'Palliative Care Specialist'), ('specialist_pharmacy', 'Pharmacy Specialist'), ('clinician_research', 'Clinician Research'), ('clinician', 'Clinician')], default='supervisor', max_length=30),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='agent_type',
            field=models.CharField(blank=True, choices=[('supervisor', 'Supervisor'), ('care_coordinator', 'Care Coordinator'), ('nurse_triage', 'Nurse Triage'), ('documentation', 'Documentation'), ('specialist_cardiology', 'Cardiology Specialist'), ('specialist_social_work', 'Social Work Specialist'), ('specialist_nutrition', 'Nutrition Specialist'), ('specialist_pt_rehab', 'PT/Rehab Specialist'), ('specialist_palliative', 'Palliative Care Specialist'), ('specialist_pharmacy', 'Pharmacy Specialist'), ('clinician_research', 'Clinician Research'), ('clinician', 'Clinician')], max_length=30),
        ),
    ]
