# Generated by Django 5.1.15 on 2026-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentconversation_clinician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20),
        ),
    ]
