# Generated by Django 5.1.15 on 2026-03-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agentmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='original_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='source_language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='translated',
            field=models.BooleanField(default=False),
        ),
    ]
