# Generated by Django 5.1.15 on 2026-03-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_add_translation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentconversation',
            name='escalation_reason',
        ),
    ]
