# Generated by Django 5.1.15 on 2026-04-01 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_remove_conversation_escalation_reason'),
        ('knowledge', '0003_qwen3_embedding_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportGroupReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona_id', models.CharField(max_length=20)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agents_support_group_reaction',
            },
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='conversation_type',
            field=models.CharField(choices=[('care_team', 'Care Team'), ('support_group', 'Support Group')], default='care_team', max_length=20),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='generation_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='persona_memories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='generation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='persona_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='conversation_excerpt',
            field=models.TextField(blank=True, help_text='Verbatim triggering message + recent messages for SG escalations'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['conversation', 'persona_id', 'created_at'], name='idx_agent_msg_persona'),
        ),
        migrations.AddConstraint(
            model_name='agentmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('persona_id__isnull', False)), fields=('conversation', 'persona_id', 'generation_id'), name='uq_agent_msg_persona_generation'),
        ),
        migrations.AddField(
            model_name='supportgroupreaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='agents.agentmessage'),
        ),
        migrations.AddConstraint(
            model_name='supportgroupreaction',
            constraint=models.UniqueConstraint(fields=('message', 'persona_id'), name='uq_reaction_message_persona'),
        ),
    ]
