# Generated by Django 5.1.15 on 2026-03-21 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0005_alter_agentmessage_role'),
        ('pathways', '0002_pathwaymilestone_patientmilestonecheckin'),
        ('patients', '0003_phase4_caregiver_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('one_time', 'One Time'), ('on_demand', 'On Demand')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('escalation_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_assignments', to='pathways.patientpathway')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignments', to='patients.patient')),
            ],
            options={
                'db_table': 'surveys_assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('category', models.CharField(choices=[('cardiac', 'Cardiac'), ('mental_health', 'Mental Health'), ('general', 'General'), ('symptom_check', 'Symptom Check'), ('custom', 'Custom')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_standard', models.BooleanField(default=True)),
                ('estimated_minutes', models.IntegerField(default=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_instruments', to='patients.hospital')),
            ],
            options={
                'db_table': 'surveys_instrument',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('domain_scores', models.JSONField(blank=True, default=dict)),
                ('raw_scores', models.JSONField(blank=True, default=dict)),
                ('escalation_triggered', models.BooleanField(default=False)),
                ('scoring_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='surveys.surveyassignment')),
                ('escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_instances', to='agents.escalation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_instances', to='patients.patient')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='surveys.surveyinstrument')),
            ],
            options={
                'db_table': 'surveys_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='surveyassignment',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='surveys.surveyinstrument'),
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('domain', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.IntegerField()),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('likert', 'Likert Scale'), ('numeric', 'Numeric'), ('yes_no', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('free_text', 'Free Text')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('min_label', models.CharField(blank=True, default='', max_length=100)),
                ('max_label', models.CharField(blank=True, default='', max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('help_text', models.TextField(blank=True, default='')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveyinstrument')),
            ],
            options={
                'db_table': 'surveys_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('raw_value', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyinstance')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestion')),
            ],
            options={
                'db_table': 'surveys_answer',
            },
        ),
        migrations.AddIndex(
            model_name='surveyinstance',
            index=models.Index(fields=['patient', 'instrument', 'status', '-completed_at'], name='idx_surveys_instance_history'),
        ),
        migrations.AddConstraint(
            model_name='surveyinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['available', 'in_progress', 'pending'])), fields=('patient', 'instrument'), name='uq_surveys_instance_one_active'),
        ),
        migrations.AddConstraint(
            model_name='surveyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'instrument'), name='uq_surveys_assignment_active'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.UniqueConstraint(fields=('instrument', 'code'), name='uq_surveys_question_instrument_code'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('instance', 'question'), name='uq_surveys_answer_instance_question'),
        ),
    ]
