# Generated by Django 5.1.15 on 2026-03-20 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lifecycle_status',
            field=models.CharField(choices=[('pre_surgery', 'Pre-Surgery'), ('admitted', 'Admitted'), ('in_surgery', 'In Surgery'), ('post_op', 'Post-Op'), ('discharged', 'Discharged'), ('recovering', 'Recovering'), ('recovered', 'Recovered'), ('readmitted', 'Readmitted')], default='pre_surgery', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientStatusTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('pre_surgery', 'Pre-Surgery'), ('admitted', 'Admitted'), ('in_surgery', 'In Surgery'), ('post_op', 'Post-Op'), ('discharged', 'Discharged'), ('recovering', 'Recovering'), ('recovered', 'Recovered'), ('readmitted', 'Readmitted')], max_length=20)),
                ('to_status', models.CharField(choices=[('pre_surgery', 'Pre-Surgery'), ('admitted', 'Admitted'), ('in_surgery', 'In Surgery'), ('post_op', 'Post-Op'), ('discharged', 'Discharged'), ('recovering', 'Recovering'), ('recovered', 'Recovered'), ('readmitted', 'Readmitted')], max_length=20)),
                ('triggered_by', models.CharField(blank=True, help_text='Who/what triggered this transition', max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_transitions', to='patients.patient')),
            ],
            options={
                'db_table': 'patients_status_transition',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='idx_transition_patient_created')],
            },
        ),
    ]
