# Generated by Django 5.1.15 on 2026-03-20 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_phase4_lifecycle_escalation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('data_sharing_caregiver', 'Data Sharing with Caregivers'), ('data_sharing_research', 'Data Sharing for Research'), ('communication_sms', 'SMS Communication'), ('communication_email', 'Email Communication'), ('ai_interaction', 'AI-Powered Care Assistance')], max_length=30)),
                ('granted', models.BooleanField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_grants', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='patients.patient')),
            ],
            options={
                'db_table': 'patients_consent_record',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['patient', 'consent_type', 'granted_at'], name='idx_consent_patient_type_at')],
            },
        ),
    ]
