# Generated by Django 5.1.15 on 2026-03-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_phase4_caregiver_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, help_text='What they like to be called', max_length=100)),
                ('about_me', models.TextField(blank=True, help_text="Patient's own words about themselves")),
                ('living_situation', models.CharField(blank=True, help_text='Lives alone, with spouse, etc.', max_length=200)),
                ('daily_routines', models.TextField(blank=True, help_text='Morning person, evening routines, etc.')),
                ('recovery_goals', models.TextField(blank=True, help_text='What they want to get back to doing')),
                ('values', models.TextField(blank=True, help_text='Independence, family time, etc.')),
                ('concerns', models.TextField(blank=True, help_text='What worries them about recovery')),
                ('communication_style', models.CharField(blank=True, choices=[('conversational', 'Conversational and warm'), ('direct', 'Direct and to-the-point'), ('detailed', 'Detailed explanations')], max_length=50)),
                ('preferred_contact_time', models.CharField(blank=True, help_text='Morning, evening, etc.', max_length=100)),
                ('language_preferences', models.TextField(blank=True, help_text='Any language or cultural considerations')),
                ('support_network', models.TextField(blank=True, help_text='Who helps them, how often')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'patient preferences',
                'db_table': 'patients_preferences',
            },
        ),
    ]
