# Generated by Django 5.1.15 on 2026-03-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_add_patient_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpreferences',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text="Patient's preferred language for the interface and messages", max_length=10),
        ),
    ]
