# Generated by Django 5.1.15 on 2026-03-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surgery_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pathways_pathway',
            },
        ),
        migrations.CreateModel(
            name='PatientPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathways.clinicalpathway')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='patients.patient')),
            ],
            options={
                'db_table': 'pathways_patient_pathway',
                'unique_together': {('patient', 'pathway')},
            },
        ),
    ]
