# Generated by Django 5.1.15 on 2026-03-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day post-surgery when this milestone occurs')),
                ('phase', models.CharField(choices=[('early', 'Early Recovery'), ('middle', 'Middle Recovery'), ('late', 'Late Recovery')], max_length=20)),
                ('expected_symptoms', models.JSONField(blank=True, default=list)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('check_in_questions', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='pathways.clinicalpathway')),
            ],
            options={
                'db_table': 'pathways_milestone',
                'ordering': ['day'],
                'unique_together': {('pathway', 'day')},
            },
        ),
        migrations.CreateModel(
            name='PatientMilestoneCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathways.pathwaymilestone')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_checkins', to='patients.patient')),
            ],
            options={
                'db_table': 'pathways_patient_milestone_checkin',
                'unique_together': {('patient', 'milestone')},
            },
        ),
    ]
