# Generated by Django 5.1.15 on 2026-04-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0002_pathwaymilestone_patientmilestonecheckin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientMilestoneCheckin',
        ),
    ]
