# Generated by Django 5.1.15 on 2026-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_patients', models.IntegerField(default=0)),
                ('active_patients', models.IntegerField(default=0)),
                ('new_patients', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('escalations', models.IntegerField(default=0)),
                ('critical_escalations', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily metrics',
                'db_table': 'analytics_daily_metrics',
                'ordering': ['-date'],
            },
        ),
    ]
