# Generated by Django 5.1.15 on 2026-03-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('patients', '0003_phase4_caregiver_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetrics',
            name='acknowledged_escalations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='active_patients_with_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='avg_acknowledgment_time_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='checkin_completion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='checkin_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='checkin_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='discharges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='NULL = cross-hospital aggregate row', null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.hospital'),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='pending_escalations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='readmission_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='readmissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='resolved_escalations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='sla_breaches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailymetrics',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailymetrics',
            unique_together={('date', 'hospital')},
        ),
    ]
