# Generated by Django 5.1.15 on 2026-03-19 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', help_text='External reference (e.g. Twilio SID) for status correlation', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'verbose_name_plural': 'notification deliveries',
                'db_table': 'notifications_delivery',
                'indexes': [models.Index(fields=['notification', 'channel'], name='idx_delivery_notif_channel'), models.Index(fields=['status', 'created_at'], name='idx_delivery_status_created')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('notification_type', models.CharField(choices=[('escalation', 'Escalation'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('update', 'Update')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (notifications deferred, not dropped)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='patients.patient')),
            ],
            options={
                'db_table': 'notifications_preference',
                'constraints': [models.UniqueConstraint(fields=('patient', 'channel', 'notification_type'), name='uniq_patient_channel_type')],
            },
        ),
    ]
