# Generated by Django 5.1.15 on 2026-03-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_delivery_and_preference_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('escalation', 'Escalation'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('update', 'Update'), ('celebration', 'Celebration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('escalation', 'Escalation'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('update', 'Update'), ('celebration', 'Celebration')], max_length=20),
        ),
    ]
