# Generated by Django 5.1.15 on 2026-04-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type_and_more'),
        ('patients', '0005_add_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('push', 'Push'), ('sms', 'SMS'), ('email', 'Email')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('push', 'Push'), ('sms', 'SMS'), ('email', 'Email')], max_length=10),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('token', models.CharField(help_text='FCM registration token', max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='e.g. iPhone 15, Pixel 8', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='patients.patient')),
            ],
            options={
                'db_table': 'notifications_device_token',
            },
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Set for push deliveries (one delivery per device token)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.devicetoken'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['patient', 'is_active'], name='idx_device_patient_active'),
        ),
    ]
