# Generated by Django 5.1.15 on 2026-04-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='Patient timezone (e.g. America/New_York) for scheduling and date calculations', max_length=50),
        ),
    ]
